### PR TITLE
Lombok integration

### PR DESCRIPTION
**Pull request by Nugs**

### CODE REVIEW

**Comment by aminmc** [comment]
We need to update the back end service as well, otherwise you'll get bad request from the service.

**Comment by MarkPaxton** [comment]
@aminmc can you point me to the api for the backend service? I was it expecting an amount and not bigdecimal?

**Comment by aminmc** [comment]
@MarkPaxton You'll need to check the self service time to pay. The code was done based on the document created by Dominic which looks like it has changed.  The original document had an object which took a value and currency.

**Comment by Nugs** [comment]
Closing as merged in to Nedda's branch

**Pull request closed without merging**
